server:
  port: 8082
  contextPath: /user-aggregate-application
---

spring:
  profiles.active: dev
---
spring:
  profiles: dev
  logging:
    file: logs/user_aggregate.log
    pattern:
      console: "%d %-5level %logger : %msg%n"
      file: "%d %-5level [%thread] %logger : %msg%n"
    level:
      org.springframework.web: DEBUG
      com.springboot.app.controllers: DEBUG
      org.hibernate: DEBUG