server:
  port: 8080
  contextPath: /user-application
---

spring:
  profiles.active: dev
---
spring:
  profiles: dev
  logging:
    path: logs/dev_app.log
    pattern:
      console: "%d %-5level %logger : %msg%n"
      file: "%d %-5level [%thread] %logger : %msg%n"
    level:
      org.springframework.web: DEBUG
      com.rest.userapp.controllers: DEBUG
      org.hibernate: DEBUG
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:mysql://localhost:3306/pnc_user_db
    username: testuser
    password: testuser@123
    driverClassName: com.mysql.jdbc.Driver